import { BuildingInstance } from "./game.types";
import {
  BuildingType,
  WorkerType,
  BuildingDefinition,
  WorkerDefinition,
} from "./economy.types";

export const BUILDING_DEFINITIONS: Record<BuildingType, BuildingDefinition> = {
  organHarvester: {
    type: "organHarvester",
    name: "Organ Harvester",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 1 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1, sepulcherStone: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    ],
    workerSlots: { timberExecutioner: 1 },
    allowedTerrain: ["scarredEarth", "weepingForest"],
    requiresRoadConnection: true,
    extraction: {
      resource: "sinewTimber",
      amountPerCycle: 1,
      cycleTimeSec: 12,
    },
    description: "Converts living forest into structural obedience.",
  },

  seedOfTheHowlingRoot: {
    type: "seedOfTheHowlingRoot",
    name: "Seed of the Howling Root",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 1 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
    ],
    workerSlots: { rootCantor: 1 },
    allowedTerrain: ["scarredEarth", "weepingForest"],
    requiresRoadConnection: true,
    description: "Replants the scream where supply has thinned.",
  },

  millOfGnashing: {
    type: "millOfGnashing",
    name: "Mill of Gnashing",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
      { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    ],
    workerSlots: { gnashSawyer: 1 },
    recipeIds: ["rendSinewTimber"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["sinewTimber"],
    outputPriority: ["toothPlanks"],
    description: "Its rotational theology is efficient.",
  },

  sepulcherQuarry: {
    type: "sepulcherQuarry",
    name: "Sepulcher Quarry",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 1 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1, sepulcherStone: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    ],
    workerSlots: { graveToothBreaker: 1 },
    allowedTerrain: ["ribMountain", "cathedralRock", "scarredEarth"],
    requiresRoadConnection: true,
    extraction: {
      resource: "sepulcherStone",
      amountPerCycle: 1,
      cycleTimeSec: 14,
    },
    description: "Stone extracted like molars from the dead.",
  },

  wombWell: {
    type: "wombWell",
    name: "Womb Well",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 1, sepulcherStone: 1 } },
    upgradeCosts: [
      { resources: { sepulcherStone: 1 } },
      { resources: { toothPlanks: 1, sepulcherStone: 1 } },
    ],
    workerSlots: { wellSupplicant: 1 },
    allowedTerrain: ["scarredEarth", "ashBog"],
    requiresRoadConnection: true,
    extraction: {
      resource: "amnioticWater",
      amountPerCycle: 1,
      cycleTimeSec: 10,
    },
    description: "Draws pale fluid from the maternal deep.",
  },

  shoreOfHooks: {
    type: "shoreOfHooks",
    name: "Shore of Hooks",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 1 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
    ],
    workerSlots: { hookFisher: 1 },
    allowedTerrain: ["scarredEarth", "placentaLake"],
    requiresRoadConnection: true,
    extraction: {
      resource: "eyelessFish",
      amountPerCycle: 1,
      cycleTimeSec: 15,
    },
    description: "The fish are blind because the lake learned first.",
  },

  fieldOfMouths: {
    type: "fieldOfMouths",
    name: "Field of Mouths",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1, sepulcherStone: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    ],
    workerSlots: { mouthFarmer: 1 },
    allowedTerrain: ["scarredEarth", "ashBog"],
    requiresRoadConnection: true,
    extraction: {
      resource: "marrowGrain",
      amountPerCycle: 1,
      cycleTimeSec: 18,
    },
    description: "The crop whispers when stepped on.",
  },

  dustCathedralMill: {
    type: "dustCathedralMill",
    name: "Dust Cathedral Mill",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
      { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    ],
    workerSlots: { dustMiller: 1 },
    recipeIds: ["grindMarrowGrain"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["marrowGrain"],
    outputPriority: ["boneDust"],
    description: "Flour production for a morally compromised state.",
  },

  ovenOfLastBread: {
    type: "ovenOfLastBread",
    name: "Oven of Last Bread",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
      { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    ],
    workerSlots: { ovenAcolyte: 1 },
    recipeIds: ["bakeFuneralLoaf"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["boneDust", "amnioticWater"],
    outputPriority: ["funeralLoaf"],
    description: "Where hunger becomes policy and policy becomes crust.",
  },

  styOfConsumption: {
    type: "styOfConsumption",
    name: "Sty of Consumption",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1, sepulcherStone: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    ],
    workerSlots: { styKeeper: 1 },
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    extraction: {
      resource: "pigFleshMass",
      amountPerCycle: 1,
      cycleTimeSec: 20,
    },
    description: "A biomass solution with hooves.",
  },

  houseOfFlensing: {
    type: "houseOfFlensing",
    name: "House of Flensing",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
      { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    ],
    workerSlots: { flenser: 1 },
    recipeIds: ["flensePigMass"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["pigFleshMass"],
    outputPriority: ["flensedMeat", "saintFat"],
    description: "Separates nutrition from sacrament.",
  },

  coalWound: {
    type: "coalWound",
    name: "Coal Wound",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 3 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
      { resources: { toothPlanks: 3, sepulcherStone: 3 } },
    ],
    workerSlots: { deepVeinMiner: 1 },
    allowedTerrain: ["ribMountain", "cathedralRock"],
    requiresRoadConnection: true,
    extraction: {
      resource: "graveCoal",
      amountPerCycle: 1,
      cycleTimeSec: 20,
    },
    description: "A cavity in the mountain that exhales fuel.",
  },

  ironVeinPit: {
    type: "ironVeinPit",
    name: "Iron Vein Pit",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 3 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
      { resources: { toothPlanks: 3, sepulcherStone: 3 } },
    ],
    workerSlots: { deepVeinMiner: 1 },
    allowedTerrain: ["ribMountain", "cathedralRock"],
    requiresRoadConnection: true,
    extraction: {
      resource: "veinIronOre",
      amountPerCycle: 1,
      cycleTimeSec: 22,
    },
    description: "Iron drawn from the subterranean circulatory system.",
  },

  goldCatacomb: {
    type: "goldCatacomb",
    name: "Gold Catacomb",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 3 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
      { resources: { toothPlanks: 3, sepulcherStone: 3 } },
    ],
    workerSlots: { deepVeinMiner: 1 },
    allowedTerrain: ["ribMountain", "cathedralRock"],
    requiresRoadConnection: true,
    extraction: {
      resource: "cathedralGoldOre",
      amountPerCycle: 1,
      cycleTimeSec: 24,
    },
    description: "Wealth mined from the after-chambers.",
  },

  bloodSmeltery: {
    type: "bloodSmeltery",
    name: "Blood Smeltery",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
      { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    ],
    workerSlots: { smelterMonk: 1 },
    recipeIds: ["smeltVeinIron"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["veinIronOre", "graveCoal"],
    outputPriority: ["veinIronBar", "lungAsh"],
    description: "Transforms geology into instruments of intent.",
  },

  haloLiquefier: {
    type: "haloLiquefier",
    name: "Halo Liquefier",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
      { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    ],
    workerSlots: { smelterMonk: 1 },
    recipeIds: ["meltHaloGold"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["cathedralGoldOre", "graveCoal"],
    outputPriority: ["haloGoldBar", "lungAsh"],
    description: "Turns sanctity into payroll.",
  },

  instrumentCrucible: {
    type: "instrumentCrucible",
    name: "Instrument Crucible",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
      { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    ],
    workerSlots: { painArtisan: 1 },
    recipeIds: ["forgeTormentInstrument"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["veinIronBar"],
    outputPriority: ["tormentInstrument"],
    description: "Produces civilizational leverage.",
  },

  bladeVestry: {
    type: "bladeVestry",
    name: "Blade Vestry",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 1 } },
      { resources: { toothPlanks: 3, sepulcherStone: 2 } },
    ],
    workerSlots: { painArtisan: 1 },
    recipeIds: ["forgeRibBlade"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["veinIronBar"],
    outputPriority: ["ribBlade"],
    description: "Produces persuasive metal.",
  },

  skinStitchery: {
    type: "skinStitchery",
    name: "Skin Stitchery",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1, sepulcherStone: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    ],
    workerSlots: { painArtisan: 1 },
    recipeIds: ["stitchSkinWall"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["toothPlanks", "saintFat"],
    outputPriority: ["skinWall"],
    description: "Armor with unfortunate texture.",
  },

  vaultOfDigestiveStone: {
    type: "vaultOfDigestiveStone",
    name: "Vault of Digestive Stone",
    maxLevel: 2,
    buildCost: { resources: { toothPlanks: 5, sepulcherStone: 4 } },
    upgradeCosts: [{ resources: { toothPlanks: 3, sepulcherStone: 3 } }],
    workerSlots: { burdenThrall: 2 },
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    description: "A warehouse pretending to be a stomach.",
  },

  pitOfWarBirth: {
    type: "pitOfWarBirth",
    name: "Pit of War Birth",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 4, sepulcherStone: 3 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 2, ribBlade: 1 } },
      { resources: { toothPlanks: 3, sepulcherStone: 3, skinWall: 1 } },
    ],
    workerSlots: { warInfant: 4 },
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    description: "Converts inventory into military childhood.",
  },

  spireOfJurisdiction: {
    type: "spireOfJurisdiction",
    name: "Spire of Jurisdiction",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 4, sepulcherStone: 4 } },
    upgradeCosts: [
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
      { resources: { toothPlanks: 3, sepulcherStone: 3 } },
    ],
    workerSlots: { warInfant: 2 },
    allowedTerrain: ["scarredEarth", "cathedralRock"],
    requiresRoadConnection: true,
    territoryInfluence: 4,
    description: "Marks where the state is allowed to keep existing.",
  },

  refectoryOfSalt: {
    type: "refectoryOfSalt",
    name: "Refectory of Salt",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1, sepulcherStone: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    ],
    workerSlots: { saltPriest: 1 },
    recipeIds: ["refineBrainSalt"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["eyelessFish"],
    outputPriority: ["brainSalt"],
    description: "Preserves thought by pulverizing its source.",
  },

  fatRenderer: {
    type: "fatRenderer",
    name: "Fat Renderer",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1, sepulcherStone: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    ],
    workerSlots: { fatBoiler: 1 },
    recipeIds: ["renderSaintFat"],
    allowedTerrain: ["scarredEarth"],
    requiresRoadConnection: true,
    inputPriority: ["saintFat"],
    outputPriority: ["saintFat"],
    description: "A blasphemous efficiency loop.",
  },

  ashPress: {
    type: "ashPress",
    name: "Ash Press",
    maxLevel: 3,
    buildCost: { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    upgradeCosts: [
      { resources: { toothPlanks: 1, sepulcherStone: 1 } },
      { resources: { toothPlanks: 2, sepulcherStone: 2 } },
    ],
    workerSlots: { ashCollector: 1 },
    recipeIds: ["compressAsh"],
    allowedTerrain: ["scarredEarth", "ashBog"],
    requiresRoadConnection: true,
    inputPriority: ["lungAsh"],
    outputPriority: ["graveCoal"],
    description: "Recycles exhaustion into further industry.",
  },
};

export const WORKER_DEFINITIONS: Record<WorkerType, WorkerDefinition> = {
  burdenThrall: {
    type: "burdenThrall",
    name: "Burden Thrall",
    moveSpeed: 1,
    canCarry: true,
    carryCapacity: 1,
    description: "The spine of logistics and the first to collapse.",
  },
  fleshMason: {
    type: "fleshMason",
    name: "Flesh Mason",
    moveSpeed: 1,
    canCarry: true,
    carryCapacity: 1,
    description: "Builds durable shapes from regrettable parts.",
  },
  timberExecutioner: {
    type: "timberExecutioner",
    name: "Timber Executioner",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Arboreal death specialist.",
  },
  rootCantor: {
    type: "rootCantor",
    name: "Root Cantor",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Sings reforestation into traumatized ground.",
  },
  gnashSawyer: {
    type: "gnashSawyer",
    name: "Gnash Sawyer",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Splits structure from scream.",
  },
  graveToothBreaker: {
    type: "graveToothBreaker",
    name: "Grave-Tooth Breaker",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Miner of stone and dental metaphors.",
  },
  wellSupplicant: {
    type: "wellSupplicant",
    name: "Well Supplicant",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Draws fluid from sacred geology.",
  },
  hookFisher: {
    type: "hookFisher",
    name: "Hook Fisher",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Collects protein from blind water.",
  },
  mouthFarmer: {
    type: "mouthFarmer",
    name: "Mouth Farmer",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Tends crops that ask to be fed back.",
  },
  dustMiller: {
    type: "dustMiller",
    name: "Dust Miller",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Turns field into powder.",
  },
  ovenAcolyte: {
    type: "ovenAcolyte",
    name: "Oven Acolyte",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Bakes state-issued grief.",
  },
  styKeeper: {
    type: "styKeeper",
    name: "Sty Keeper",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Feeds the biomass with discipline.",
  },
  flenser: {
    type: "flenser",
    name: "Flenser",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Distinguishes edible from devotional.",
  },
  deepVeinMiner: {
    type: "deepVeinMiner",
    name: "Deep Vein Miner",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Works inside the body of the world.",
  },
  smelterMonk: {
    type: "smelterMonk",
    name: "Smelter Monk",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Heat, ore, repetition, doctrine.",
  },
  painArtisan: {
    type: "painArtisan",
    name: "Pain Artisan",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Specializes in useful cruelty.",
  },
  warInfant: {
    type: "warInfant",
    name: "War Infant",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Freshly instructed in borders.",
  },
  saltPriest: {
    type: "saltPriest",
    name: "Salt Priest",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Preserves memory by reducing it to mineral.",
  },
  fatBoiler: {
    type: "fatBoiler",
    name: "Fat Boiler",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Manages the slick side of the economy.",
  },
  ashCollector: {
    type: "ashCollector",
    name: "Ash Collector",
    moveSpeed: 1,
    canCarry: false,
    carryCapacity: 0,
    description: "Recovers failure as fuel.",
  },
};

export function getBuildingDefinition(
  building: BuildingInstance
): BuildingDefinition {
  return BUILDING_DEFINITIONS[building.type];
}

export function getWorkerDefinition(type: WorkerType): WorkerDefinition {
  return WORKER_DEFINITIONS[type];
}
